DEFAULT_SENTENCE_PAUSE_S = 0.2

DEFAULT_WAVEGLOW = "pretrained_v3"
DEFAULT_SIGMA = 1.0
DEFAULT_DENOISER_STRENGTH = 0.0005
DEFAULT_MAX_DECODER_STEPS = 3000
DEFAULT_MEL_INFO_COPY_PATH = "/tmp/mel_out.json"
