# padding, used for unknown symbols and in training for no symbols
DEFAULT_PADDING_SYMBOL = "_"

DEFAULT_CSV_SEPERATOR = "\t"

DEFAULT_PADDING_ACCENT = "none"

SHARED_SYMBOLS = [DEFAULT_PADDING_SYMBOL]
SHARED_SYMBOLS_COUNT = len(SHARED_SYMBOLS)
NOT_INFERABLE_SYMBOL_MARKER = "█"
